In [37]:
import string
import traceback
import re
import os
import json
import pickle
import glob
from PIL import Image
from time import time

from sklearn.model_selection import train_test_split

import cv2
import numpy as np
from numpy import array
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from tensorflow import keras
import tensorflow as tf
import tensorflow.compat.v1
from tensorflow.keras import backend as K
from tensorflow.keras.datasets import mnist
from tensorflow.keras import utils
from keras.layers.embeddings import Embedding
from keras.layers.merge import add
from keras.preprocessing import image
from keras.preprocessing.text import Tokenizer
from keras.layers.wrappers import Bidirectional
from keras.layers.merge import add
from keras.applications.inception_v3 import InceptionV3
from keras.applications.inception_v3 import preprocess_input
from tensorflow.keras.utils import to_categorical
from keras.preprocessing import sequence
from keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import (Attention, Layer,
                                     Add,concatenate,
                                     Input, 
                                     Dense,  
                                     LSTM, Bidirectional, GRU,
                                     ZeroPadding2D, 
                                     Convolution2D, Conv2D, 
                                     GlobalAveragePooling2D, GlobalAvgPool2D, GlobalMaxPooling2D, GlobalMaxPool2D, 
                                     AveragePooling2D, AvgPool2D, MaxPooling2D, MaxPool2D,
                                     Flatten,
                                     BatchNormalization, 
                                     Dropout)

from tensorflow.keras.layers import (Activation, 
                                     ReLU, 
                                     LeakyReLU, 
                                     Softmax)

from tensorflow.keras.optimizers import (SGD,
                                         Adam,
                                         Adagrad,
                                         Adadelta,
                                         RMSprop,
                                         Nadam)

from tensorflow.keras.preprocessing.image import ImageDataGenerator, img_to_array, array_to_img, load_img

# from tensorflow.keras.applications.vgg16 import VGG16

from tqdm import tqdm
from tensorflow.keras.applications.vgg16 import VGG16
import pyphen
import eng_to_ipa as ipa  # international phonetic aphabet

In [33]:
df = pd.DataFrame(columns=['id', 'ROCE(%)', 'Income Growth(%)','Sale Growth(%)', 'Debt Equity Ratio'])

In [42]:
df['id'] = np.arange(1, 7778)
df['ROCE(%)'] = np.random.normal(1, 100, size=(7777, ))
df['Income Growth(%)'] = np.random.normal(1, 100, size=(7777, ))
df['Sale Growth(%)'] = np.random.normal(1, 100, size=(7777, ))
df['Debt Equity Ratio'] = np.random.uniform(-1, 0.5, size=(7777, ))
df.head()

   id     ROCE(%)  Income Growth(%)  Sale Growth(%)  Debt Equity Ratio
0   1  105.502993        137.380475      -38.862170           0.493548
1   2 -290.386986         91.287783      -92.688491          -0.667857
2   3  -34.064807        -20.420386       16.818664           0.325987
3   4    9.708701         67.468809      -43.614209           0.432126
4   5  123.381079        -97.451894       29.146933           0.297247

In [43]:
df.to_csv('stock_data.csv')